### ISSUE TITLE
f.sortable not a function errors

### ISSUE THREAD

**Issue by dustinsmith1024** [mb21/JSONedit#47]
I keep getting these f.sortable is not a function errors.  We have multiple JSON Editor's on our page and they all seem to throw the error.

Everything works, fine I would just like to clean up the console logs.

Any ideas?

```js
angular.js:14324 TypeError: f.sortable is not a function
    at Object.link (http://localhost:8088/assets/vendor/angular-ui-sortable/sortable.min.js:1:2660)
    at http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:1291:18
    at invokeLinkFn (http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:10249:9)
    at nodeLinkFn (http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:9638:11)
    at compositeLinkFn (http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:8878:13)
    at nodeLinkFn (http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:9632:11)
    at compositeLinkFn (http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:8878:13)
    at publicLinkFn (http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:8743:30)
    at Object.link (http://localhost:8088/assets/vendor/jsonEdit/v0.2.0/js/directives.js:253:29)
    at http://localhost:8088/assets/vendor/angular/1.6.0/angular.js:1291:18 <ol class="arrayOl ng-pristine ng-untouched ng-valid" ui-sortable="sortableOptions" ng-model="child">
```

**Comment by mb21** [comment]
have you included the following?

    <script src="bower_components/json-edit/bower_components/angular-ui-sortable/sortable.min.js"></script>

**Comment by dustinsmith1024** [comment]
Yea its there and loading fine.  We are using require js to bring it in though.

**Comment by mb21** [comment]
you'll have to make sure that require js loads it before angular tries to use it...
